# Generated by Django 4.2.11 on 2024-04-28 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date')),
                ('temperature_data', models.JSONField(verbose_name='temperature_data')),
            ],
        ),
        migrations.CreateModel(
            name='AISummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.TextField()),
                ('weather', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='weather.weather')),
            ],
        ),
    ]
