# Generated by Django 4.2.11 on 2024-04-13 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('weather_date', models.DateTimeField(primary_key=True, serialize=False, verbose_name='date')),
                ('temperature_data', models.JSONField(verbose_name='temperature_data')),
            ],
        ),
    ]
